[package]
name = "cap_identifier_smoke"
version = "0.1.0"
edition = "2021"

[dependencies]
cap_identifier = { path = "../.." }
cap_random = { path = "../../../Random" }

[[bin]]
name = "cap_identifier_smoke"
path = "main.rs"

[workspace]
