[package]
name = "sys_vfs"
version = "0.1.0"
edition = "2021"

[lib]
name = "sys_vfs"
path = "API/lib.rs"

[dependencies]
cap_memory = { path = "../../Cap/Memory" }
cap_path = { path = "../../Cap/Path" }
prm_file = { path = "../../Prm/File" }

