[package]
name = "prm_hid_smoke"
version = "0.1.0"
edition = "2021"

[dependencies]
prm_hid = { path = "../.." }
prm_window = { path = "../../../Window" }

[[bin]]
name = "prm_hid_smoke"
path = "main.rs"
