[package]
name = "sys_task"
version = "0.1.0"
edition = "2021"

[lib]
name = "sys_task"
path = "API/lib.rs"

[dependencies]
cap_memory = { path = "../../Cap/Memory" }
sys_job = { path = "../Job" }
cap_concurrency = { path = "../../Cap/Concurrency" }
prm_threading = { path = "../../Prm/Threading" }
